// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL9kGSCm7VqbGb4Vc7jN7YtExK8x-mJ4Y',
    appId: '1:812858670577:web:7a0f8e0c8e0e0e0e0e0e0e',
    messagingSenderId: '812858670577',
    projectId: 'reeltalk-46664',
    authDomain: 'reeltalk-46664.firebaseapp.com',
    storageBucket: 'reeltalk-46664.appspot.com',
    // measurementId: 'G-XXXXXXXXXX', // Add your actual measurement ID if using Firebase Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9kGSCm7VqbGb4Vc7jN7YtExK8x-mJ4Y',
    appId: '1:812858670577:android:7a0f8e0c8e0e0e0e0e0e0e',
    messagingSenderId: '812858670577',
    projectId: 'reeltalk-46664',
    storageBucket: 'reeltalk-46664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL9kGSCm7VqbGb4Vc7jN7YtExK8x-mJ4Y',
    appId: '1:812858670577:ios:7a0f8e0c8e0e0e0e0e0e0e',
    messagingSenderId: '812858670577',
    projectId: 'reeltalk-46664',
    storageBucket: 'reeltalk-46664.appspot.com',
    iosBundleId: 'com.reeltalk.app',
  );
}
